# Generated by Django 5.0.6 on 2026-07-27 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chat_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment_mentions',
            },
        ),
        migrations.CreateModel(
            name='NoteMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_mentions',
            },
        ),
        migrations.CreateModel(
            name='TaskSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_subscribers',
            },
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_tenant__832ae0_idx',
            old_name='chat_msg_tenant__room_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_rooms_tenant__e26f4d_idx',
            old_name='chat_room_tenant__recent_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommembership',
            new_name='chat_room_m_user_id_a376c8_idx',
            old_name='chat_member_user_recent_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_tenant__14414f_idx',
            old_name='invoice_tenant__status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_tenant__3a9262_idx',
            old_name='invoice_tenant__date_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_reque_tenant__e374b2_idx',
            old_name='leave_req_tenant__status_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_reque_tenant__0f7674_idx',
            old_name='leave_req_tenant__req_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_reque_tenant__cc5436_idx',
            old_name='leave_req_tenant__start_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='meetings_tenant__775137_idx',
            old_name='meetings_tenant__start_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='meetings_tenant__3baad4_idx',
            old_name='meetings_tenant__status_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_tenant__6dbc28_idx',
            old_name='notes_tenant__content_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_tenant__dcf936_idx',
            old_name='notes_tenant__author_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__cf9a22_idx',
            old_name='notif_tenant__read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__835e41_idx',
            old_name='notif_tenant__recent_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_tenant__b802bd_idx',
            old_name='todos_tenant__owner_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_tenant__bffb71_idx',
            old_name='todos_tenant__completed_idx',
        ),
        migrations.AddField(
            model_name='commentmention',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.comment'),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_mentions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemention',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_mentions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemention',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.note'),
        ),
        migrations.AddField(
            model_name='tasksubscriber',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_subscriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubscriber',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='api.task'),
        ),
        migrations.AddField(
            model_name='tasksubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['tenant_id', 'mentioned_user'], name='comment_men_tenant__94e6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'mentioned_user'), name='uniq_comment_mentioned_user'),
        ),
        migrations.AddIndex(
            model_name='notemention',
            index=models.Index(fields=['tenant_id', 'mentioned_user'], name='note_mentio_tenant__55fbfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='notemention',
            constraint=models.UniqueConstraint(fields=('note', 'mentioned_user'), name='uniq_note_mentioned_user'),
        ),
        migrations.AddIndex(
            model_name='tasksubscriber',
            index=models.Index(fields=['tenant_id', 'task'], name='task_subscr_tenant__bc43d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubscriber',
            index=models.Index(fields=['tenant_id', 'user'], name='task_subscr_tenant__f53304_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksubscriber',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_subscriber'),
        ),
    ]
